// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtdKodpi-guY1MHViipDbKV4uGXnZx_b0',
    appId: '1:1045344710046:web:a19c9f103127dbf0bafa8f',
    messagingSenderId: '1045344710046',
    projectId: 'daily-todo-8bec9',
    authDomain: 'daily-todo-8bec9.firebaseapp.com',
    databaseURL: 'https://daily-todo-8bec9-default-rtdb.firebaseio.com',
    storageBucket: 'daily-todo-8bec9.appspot.com',
    measurementId: 'G-NSCKZX5XTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Y1P0uCCIEoqzxqQ6HBIvLWME8jsRsZs',
    appId: '1:1045344710046:android:8a70afa459ddc9a0bafa8f',
    messagingSenderId: '1045344710046',
    projectId: 'daily-todo-8bec9',
    databaseURL: 'https://daily-todo-8bec9-default-rtdb.firebaseio.com',
    storageBucket: 'daily-todo-8bec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA71k-d3hCrx0er9Hc2z4umm9xFOL8XqyA',
    appId: '1:1045344710046:ios:419953876b399dc7bafa8f',
    messagingSenderId: '1045344710046',
    projectId: 'daily-todo-8bec9',
    databaseURL: 'https://daily-todo-8bec9-default-rtdb.firebaseio.com',
    storageBucket: 'daily-todo-8bec9.appspot.com',
    iosBundleId: 'com.simprok.dailyTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA71k-d3hCrx0er9Hc2z4umm9xFOL8XqyA',
    appId: '1:1045344710046:ios:28a9ad699f5703a6bafa8f',
    messagingSenderId: '1045344710046',
    projectId: 'daily-todo-8bec9',
    databaseURL: 'https://daily-todo-8bec9-default-rtdb.firebaseio.com',
    storageBucket: 'daily-todo-8bec9.appspot.com',
    iosBundleId: 'com.simprok.dailyTodo.RunnerTests',
  );
}
